title: Nighthawk Pages 
description: "Class of 2026"
owner_name: Ansh Kumar
github_username: magic005
github_repo: "student_20266" 
baseurl: "/student_20266"
future: true
remote_theme: jekyll/minima
minima:
  nav_pages:
    - navigation/blog.md
    - navigation/search.md
    - navigation/about.md
    - projects/project1.md
    - README4YML.md
  skin: dark
  social_links:
    - { platform: github, user_url: "https://github.com/nighthawkcoders"}
    - { platform: x, user_url: "https://x.com/NighthawkCoding/" }
    - { platform: youtube, user_url: "https://www.youtube.com/@nighthawkcodingsociety2868" } 
# remote_theme: pages-themes/midnight@v0.2.0
# remote_theme: pages-themes/cayman@v0.2.0
# remote_theme: pages-themes/dinky@v0.2.0
# remote_theme: pages-themes/minimal@v0.2.0
# remote_theme: pages-themes/time-machine@v0.2.0
plugins:
  - jekyll-remote-theme
