title: Nighthawk Pages 
description: "Class of 2026"
owner_name: Ansh Kumar
github_username: magic005
github_repo: "student_20266" 
baseurl: "/student_20266"
future: true

remote_theme: jekyll/minima
# remote_theme: pages-themes/minimal@v0.2.0

minima:
  skin: dark
  social_links:
    - { platform: github, user_url: "https://github.com/nighthawkcoders"}
    - { platform: x, user_url: "https://x.com/NighthawkCoding/" }
    - { platform: youtube, user_url: "https://www.youtube.com/@nighthawkcodingsociety2868" } 

plugins:
  - jekyll-remote-theme
